// <auto-generated />
namespace EmployeeCRUD_EF_cF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UseSP : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UseSP));
        
        string IMigrationMetadata.Id
        {
            get { return "202406041932479_UseSP"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
